export const siteConfig = {
  name: "Alexis Olivero",
  title: "Website Performance, Security & Modernization Specialist",
  description:
    "I help established businesses turn slow, vulnerable, hard-to-manage websites into fast, secure platforms built to earn trust and generate qualified opportunities.",
  url: "https://oliverodev.com",
  ogImage: "https://oliverodev.com/opengraph-image",
  links: {
    instagram: "https://www.instagram.com/alexisfit97/",
    github: "https://github.com/wolfslender",
    linkedin: "https://linkedin.com/in/alexis-olivero",
    email: "contact@oliverodev.com",
  },
  author: "Alexis Olivero",
  keywords: [
    "frontend developer",
    "desarrollador frontend",
    "web developer",
    "desarrollador web",
    "react developer",
    "programador react",
    "next.js expert",
    "typescript",
    "javascript",
    "tailwind css",
    "wordpress specialist",
    "experto wordpress",
    "webflow developer",
    "desarrollador webflow",
    "seo optimization",
    "posicionamiento seo",
    "web performance",
    "optimización web",
    "ui/ux design",
    "diseño web",
    "freelance developer",
    "programador freelance",
    "hire web developer",
    "hire frontend developer",
    "contratar desarrollador web",
    "contratar desarrollador frontend",
    "web developer for hire",
    "frontend freelancer",
    "alexis olivero",
    "portfolio",
  ],
  navItems: [
    { label: "Home", href: "/" },
    { label: "Services", href: "/services" },
    { label: "Work", href: "/work" },
    { label: "Blog", href: "/blog" },
    { label: "About", href: "/about" },
    { label: "Contact", href: "/contact" },
  ],
  pluginsNavItem: { label: "Plugins", href: "/plugins" },
  testimonials: [
    {
      quote: "Limpió archivos basura y optimizó mi sitio de WordPress rápidamente sin afectar nada importante.",
      author: "farahalmn",
      role: "Verified WordPress.org reviewer",
      sourceUrl: "https://wordpress.org/plugins/oliverodev-media-audit/#reviews",
    }
  ],
}

export type SiteConfig = typeof siteConfig
