import { Code, Users, Award, Coffee, Code2, Server, Database, GitBranch, Palette, Smartphone, Zap, Rocket, Search, Globe, Layout, Shield, Brain, MessageSquare, Clock, Users2, Cloud, FileCode } from "lucide-react"

export const services = [
  {
    title: "Websites & MVPs",
    description: "A working website or MVP in weeks — not months. Strategy, UX, and build all in one package. From concept to launch, I handle everything so you can focus on growing your business.",
    icon: Layout,
    features: ["Rapid Prototyping", "Conversion-Focused UX", "CMS or App Build", "Launch Strategy"],
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    caseStudyTitle: "Cybernetips",
    color: "text-pink-500",
    bgColor: "bg-pink-500/10",
    bestFor: "Founders and growing businesses that need a new site or MVP fast.",
    timeline: "4-6 weeks",
    outcome: "A fast, premium website or MVP built to win trust, capture leads, and support growth.",
    deliverables: ["Strategy Sprint", "UX/UI Direction", "CMS or Product Build", "Launch Support"],
    quoteOptions: [
      { id: "landing-wordpress", name: "Landing Page / CMS Website", description: "Ideal for business sites, blogs, and content-driven projects. Built on a proven CMS so you can manage content yourself." },
      { id: "mvp-framework", name: "MVP with Framework", description: "Custom-built web app with React, Next.js, or Node. Perfect for SaaS products, interactive platforms, and scalable projects." },
    ],
  },
  {
    title: "Web Performance Optimization",
    description: "Slow sites kill conversions. I audit, optimize, and fine-tune every layer — from server config to frontend assets — so your site loads in under 2 seconds and scores 90+ on Core Web Vitals.",
    icon: Zap,
    features: ["Performance Audit", "Core Web Vitals Optimization", "Image & Asset Optimization", "Caching Strategy", "CDN Setup"],
    technologies: ["Lighthouse", "PageSpeed Insights", "CDN", "Caching"],
    caseStudyTitle: "Co-Active Training Institute",
    color: "text-yellow-500",
    bgColor: "bg-yellow-500/10",
    bestFor: "Sites that are slow, have high bounce rates, or are losing conversions due to load time.",
    timeline: "2-4 weeks",
    outcome: "A fast website that loads in under 2 seconds, scores 90+ on Core Web Vitals, and keeps visitors engaged.",
    deliverables: ["Performance Audit Report", "Optimization Roadmap", "Implementation", "Before/After Metrics"],
    regionPrices: {
      latam: [
        { label: "Auditoría", min: 200, max: 350 },
        { label: "Implementación de fixes", min: 400, max: 1200 },
      ],
      usa: [
        { label: "Audit", min: 400, max: 600 },
        { label: "Fix Implementation", min: 1000, max: 3000 },
      ],
    },
  },
  {
    title: "Web Security",
    description: "Protect your website and your users. I implement comprehensive security measures — from firewalls and malware scanning to secure authentication and regular audits — so you can sleep at night.",
    icon: Shield,
    features: ["Security Audit", "Malware Scanning & Removal", "Firewall Setup", "SSL/TLS Configuration", "Ongoing Monitoring"],
    technologies: ["Security Headers", "SSL/TLS", "WAF", "Malware Detection"],
    caseStudyTitle: "Cybernetips",
    color: "text-green-500",
    bgColor: "bg-green-500/10",
    bestFor: "Businesses that handle sensitive data, process payments, or want to prevent costly security breaches.",
    timeline: "1-3 weeks",
    outcome: "A hardened, secure website protected against common vulnerabilities and threats.",
    deliverables: ["Security Audit Report", "Hardening Implementation", "Monitoring Setup", "Incident Response Plan"],
    pricingNote: "El alcance varía según el tamaño del sitio, la cantidad de usuarios y los niveles de acceso requeridos. Evaluamos tu caso y te damos una cotización justa.",
  },
  {
    title: "Hacked Site Recovery",
    description: "Your site's been hacked. Don't panic. I'll clean the malware, close the vulnerabilities, restore your content, and implement protections to prevent it from happening again. Fast response, minimal downtime.",
    icon: Server,
    features: ["Emergency Malware Cleanup", "Vulnerability Patching", "Content Restoration", "Security Hardening", "Post-Recovery Monitoring"],
    technologies: ["Malware Detection", "Backup Recovery", "File Integrity Monitoring", "Security Scanning"],
    caseStudyTitle: "Cybernetips",
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    bestFor: "Site owners whose website has been compromised, defaced, or infected with malware.",
    timeline: "24-72 hours (emergency)",
    outcome: "A clean, restored website with strengthened security to prevent future attacks.",
    deliverables: ["Malware Cleanup", "Vulnerability Report", "Security Hardening", "Recovery Documentation"],
    regionPrices: {
      latam: [
        { label: "Recuperación", min: 120, max: 300 },
      ],
      usa: [
        { label: "Recovery", min: 300, max: 800 },
      ],
    },
  },
  {
    title: "Platform Migration",
    description: "Moving from one platform to another without losing SEO, content, or functionality. Whether you're switching CMS platforms or rebuilding on a modern stack, I handle the migration so your business doesn't skip a beat.",
    icon: Globe,
    features: ["SEO Preservation", "Content Migration", "Data Integrity Assurance", "Zero-Downtime Migration", "Post-Migration Support"],
    technologies: ["Next.js", "Webflow", "Sanity", "API Integration"],
    caseStudyTitle: "Truenorth Corporation",
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
    bestFor: "Companies stuck on outdated platforms who want better performance, usability, and maintainability.",
    timeline: "3-8 weeks",
    outcome: "A modern, faster, more maintainable platform with zero data loss and preserved SEO rankings.",
    deliverables: ["Migration Strategy", "Data Migration", "SEO Preservation", "Post-Launch Support"],
    regionPrices: {
      latam: [
        { label: "Migración mismo CMS", min: 250, max: 700 },
        { label: "Migración cambio de CMS", min: 1200, max: 3000 },
      ],
      usa: [
        { label: "Same CMS Migration", min: 600, max: 1500 },
        { label: "Cross-CMS Migration", min: 2500, max: 6000 },
      ],
    },
  },
]

export const hero = {
  title: {
    prefix: "Websites that actually",
    highlight: "bring in business.",
  },
  roles: ["UI/UX that converts", "SEO + Speed", "Webflow / WordPress / Next.js", "I do the work myself"],
  description: "I build and fix websites for businesses that need them to load fast, look legit, and turn visitors into paying customers. No fluff, no agencies — just me.",
  proof: ["I reply within 24h", "Built for SEO from day one", "Launch support included"],
  location: "Based in Santo Domingo · Working worldwide",
  buttons: {
    primary: "Book a Strategy Call",
    secondary: "Get a Free Audit",
    downloadCv: "Download My Resume",
  },
}

export const stats = [
  { icon: Code, value: 10, label: "Years Experience", suffix: "+", prefix: "" },
  { icon: Users, value: 50, label: "Projects Delivered", suffix: "+", prefix: "" },
  { icon: Award, value: 100, label: "Client Satisfaction", suffix: "%", prefix: "" },
  { icon: Zap, value: 30, label: "Faster Load Times", suffix: "%", prefix: "" },
]

export const skills = [
  {
    icon: Code2,
    title: "Frontend",
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
    skills: ["HTML5", "CSS3", "JavaScript (ES6+)", "React.js", "Next.js", "Tailwind CSS", "Sass/LESS"],
  },
  {
    icon: Globe,
    title: "CMS & Platforms",
    color: "text-cyan-500",
    bgColor: "bg-cyan-500/10",
    skills: ["WordPress", "Webflow", "WooCommerce", "Shopify", "CPanel"],
  },
  {
    icon: Zap,
    title: "Performance",
    color: "text-yellow-500",
    bgColor: "bg-yellow-500/10",
    skills: ["SEO", "Core Web Vitals", "Accessibility (WCAG)", "Responsive Design", "Optimization"],
  },
  {
    icon: GitBranch,
    title: "Tools & DevOps",
    color: "text-purple-500",
    bgColor: "bg-purple-500/10",
    skills: ["Git", "GitHub", "Azure", "Docker", "VS Code", "Chrome DevTools"],
  },
  {
    icon: Palette,
    title: "Design",
    color: "text-pink-500",
    bgColor: "bg-pink-500/10",
    skills: ["UI/UX Principles", "Figma", "Wireframing", "Prototyping", "User-Centered Design"],
  },
  {
    icon: Shield,
    title: "Security",
    color: "text-green-500",
    bgColor: "bg-green-500/10",
    skills: ["Web Security", "Data Protection", "Secure Coding", "Server Hardening", "OWASP Top 10"],
  },
]

export const softSkills = [
  { icon: MessageSquare, label: "Communication" },
  { icon: Brain, label: "Problem Solving" },
  { icon: Users2, label: "Teamwork" },
  { icon: Clock, label: "Time Management" },
  { icon: Rocket, label: "Adaptability" },
  { icon: Palette, label: "Creativity" },
]

export const certifications = [
  {
    title: "Scrum Fundamentals Certified (SFC)",
    issuer: "VMEdu Inc.",
    date: "Feb 2025",
    credentialId: "1066047",
    credentialUrl: "#",
    icon: Users2,
    color: "text-orange-500",
    bgColor: "bg-orange-500/10",
  },
  {
    title: "Webflow 101 Certification",
    issuer: "Webflow",
    date: "Nov 2023",
    credentialId: "Alexis Olivero Canario",
    credentialUrl: "#",
    icon: Layout,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
  },

  {
    title: "Information Technology Fundamentals",
    issuer: "IBM",
    date: "May 2025",
    credentialId: "IBM-2025",
    credentialUrl: "#",
    icon: Server,
    color: "text-indigo-500",
    bgColor: "bg-indigo-500/10",
  },
  {
    title: "Hacking Ético en Acción",
    issuer: "Desafío Latam",
    date: "Mar 2025",
    credentialId: "5m77bnugwj",
    credentialUrl: "#",
    icon: Shield,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
  },
  {
    title: "Fundamentos de AWS Cloud Services",
    issuer: "LinkedIn",
    date: "Sep 2022",
    credentialId: "AWS-LI",
    credentialUrl: "#",
    icon: Cloud,
    color: "text-yellow-500",
    bgColor: "bg-yellow-500/10",
  },
  {
    title: "Azure: Bases de datos SQL",
    issuer: "LinkedIn",
    date: "Sep 2023",
    credentialId: "AZURE-SQL",
    credentialUrl: "#",
    icon: Database,
    color: "text-cyan-500",
    bgColor: "bg-cyan-500/10",
  },
  {
    title: "React Esencial",
    issuer: "LinkedIn",
    date: "Sep 2023",
    credentialId: "REACT-LI",
    credentialUrl: "#",
    icon: Code2,
    color: "text-sky-500",
    bgColor: "bg-sky-500/10",
  },
  {
    title: "Domina JavaScript",
    issuer: "LinkedIn",
    date: "Sep 2023",
    credentialId: "JS-LI",
    credentialUrl: "#",
    icon: FileCode,
    color: "text-yellow-400",
    bgColor: "bg-yellow-400/10",
  },
  {
    title: "GitHub para Programadores",
    issuer: "LinkedIn",
    date: "Jun 2023",
    credentialId: "GH-LI",
    credentialUrl: "#",
    icon: GitBranch,
    color: "text-purple-500",
    bgColor: "bg-purple-500/10",
  },
]

export const projects = [
  {
    title: "Media Audit",
    slug: "media-audit",
    description: "WordPress plugin that scans your media library to identify unused files, helping you recover storage space and improve site performance. Features smart detection, storage analysis, and an intelligent trash system.",
    image: "/projects/media-audit-pro.png",
    tags: ["WordPress", "PHP", "MySQL", "AJAX", "Freemius"],
    category: "fullstack",
    github: "https://github.com/oliverodev/media-audit",
    demo: "https://wordpress.org/plugins/oliverodev-media-audit/",
    featured: true,
    size: "medium",
    industry: "WordPress Plugins",
    projectType: "Plugin Development",
    metrics: {
      users: {
        value: "WordPress.org published",
        label: "Status"
      },
      performance: "Reduces storage by up to 40%",
      impact: "10GB+ media cleaned"
    }
  },
  {
    title: "Cybernetips",
    slug: "cybernetips",
    description: "The #1 company globally specialized in immediate response to cybersecurity incidents. Leaders in digital asset recovery and protection.",
    image: "/projects/cybernetips.png",
    tags: ["Cybersecurity", "Incident Response", "Digital Recovery", "Fullstack"],
    category: "fullstack",
    github: "#",
    demo: "https://cybernetips.com/",
    featured: true,
    size: "large",
    industry: "Cybersecurity",
    projectType: "MVP Launch",
    metrics: {
      users: "Global enterprise clients",
      performance: "24/7 incident response",
      impact: "#1 in digital asset recovery"
    }
  },
  {
    title: "Co-Active Training Institute",
    slug: "co-active-training-institute",
    description: "Ongoing fullstack development and maintenance for a global leadership training platform. Responsible for SEO strategies, performance optimization, and implementing new features for a site serving over 150k professionals worldwide.",
    image: "/projects/coactive.jpg",
    tags: ["Wordpress", "JS", "PHP", "Arlo", "Moodle", "SEO", "Performance"],
    category: "fullstack",
    github: "https://github.com/wolfslender",
    demo: "https://coactive.com/",
    featured: true,
    size: "large",
    industry: "EdTech",
    projectType: "Technical Partnership",
    metrics: {
      users: "150,000+",
      performance: "40% faster load times",
      impact: "Global reach across 60+ countries"
    },
    challenge: "Managing a high-traffic platform serving a global audience of leadership professionals while maintaining 99.9% uptime and implementing continuous feature improvements.",
    solution: "Implemented strategic performance optimizations, advanced SEO strategies, and seamless integration with Arlo and Moodle LMS platforms. Established robust monitoring and deployment pipelines.",
    impactStatement: "Enabled Co-Active to scale their digital presence to serve 150K+ professionals worldwide with zero downtime during critical training periods."
  },
  {
    title: "Departamento de Educación PR",
    slug: "departamento-de-educacion-pr",
    description:
      "Led end-to-end development of a government website for Puerto Rico. Delivered a responsive, accessible, and CMS-integrated solution aligned with public sector standards.",
    image: "/projects/departamento-educacion.jpg",
    tags: ["WordPress", "PHP", "CSS", "JavaScript"],
    category: "fullstack",
    github: "https://github.com/wolfslender",
    demo: "https://de.pr.gov/",
    industry: "Government",
    projectType: "Custom Development",
    metrics: {
      users: "Public sector platform",
      performance: "WCAG 2.1 AA compliant",
      impact: "Serving Puerto Rico's education system"
    },
    featured: true,
    size: "medium",
  },
  {
    title: "D.Med Healthcare Group",
    slug: "dmed-healthcare-group",
    description: "Developed a drag-and-drop task management app with real-time updates, team collaboration, and authentication features.",
    image: "/projects/dmed.jpg",
    tags: ["WordPress", "PHP", "CSS", "JavaScript"],
    category: "fullstack",
    github: "https://github.com/wolfslender",
    demo: "https://dmed-healthcare.com/",
    featured: false,
    size: "medium",
  },
  {
    title: "Acuastock",
    slug: "acuastock",
    description: "Specialized e-commerce for ornamental fish, aquariums, and accessories. Features product catalog, import services, and comprehensive aquatic supplies.",
    image: "/projects/acuastock.jpg",
    tags: ["WordPress", "PHP", "CSS", "JavaScript"],
    category: "fullstack",
    github: "#",
    demo: "https://acuastock.com/",
    featured: false,
    size: "large",
  },
  {
    title: "Keitel De Luna - Cybersecurity Analyst | IT Portfolio",
    slug: "keitel-de-luna-cybersecurity-analyst",
    description: "Certified professional with credentials from IBM and Google. Expert in building secure systems, vulnerability management, and fostering efficient technical environments.",
    image: "/projects/Keitel-De-Luna.png",
    tags: ["Cybersecurity", "IT Support", "Vulnerability Management"],
    category: "fullstack",
    github: "#",
    demo: "https://keiteldeluna.com/",
    featured: false,
    size: "large",
  },
  {
    title: "CST Puerto Rico Website",
    slug: "cst-puerto-rico-website",
    description: "Government project focused on traffic safety. Includes CMS, incident reports, interactive maps, and community feedback tools.",
    image: "/projects/cst-puerto-rico.jpg",
    tags: ["Webflow", "JS", "Tailwind CSS"],
    category: "fullstack",
    github: "https://github.com/wolfslender",
    demo: "https://www.cst.pr.gov/",
    featured: true,
    industry: "Government",
    projectType: "Custom Development",
    size: "large",
  },
  {
    title: "Truenorth Corporation",
    slug: "truenorth-corporation",
    description: "Migrated corporate website from WordPress to Webflow, rebuilding the frontend and integrating custom API functionalities for better performance.",
    image: "/projects/truenorth.jpg",
    tags: ["Webflow", "React", "Node.js"],
    category: "frontend",
    github: "https://github.com/wolfslender",
    demo: "https://www.truenorth.pr/",
    industry: "Enterprise",
    projectType: "Migration",
    metrics: {
      users: "Marketing team autonomy",
      performance: "45 → 95 speed score",
      impact: "Faster updates with cleaner CMS"
    },
    challenge: "The old marketing site was difficult to update, slower than it should be, and created unnecessary dependency on developers for routine content changes.",
    solution: "Rebuilt the experience in Webflow, preserved SEO-critical structure, and added integrations that made updates easier for the internal team.",
    impactStatement: "The final result gave the brand more control over content, better performance, and a more polished digital presence for enterprise audiences.",
    featured: false,
    size: "medium",
  },
  {
    title: "GovValue",
    slug: "govvalue",
    description: "Dynamic blog system with SEO optimization, author management, and custom call-to-action banners to attract new users.",
    image: "/projects/govvalue.jpg",
    tags: ["React", "JavaScript", "CSS Grid", "SEO"],
    category: "frontend",
    github: "https://github.com/wolfslender",
    demo: "https://govvalue.com/",
    featured: false,
    size: "medium",
  },
  {
    title: "AESAN Website",
    slug: "aesan-website",
    description: "Official website for the Government of Puerto Rico. Responsive, accessible platform aligned with public health communication standards.",
    image: "/projects/aesan.jpg",
    tags: ["WordPress", "PHP", "CSS", "JavaScript"],
    category: "fullstack",
    github: "https://github.com/wolfslender",
    demo: "https://aesan.dde.pr/",
    industry: "Government",
    projectType: "Custom Development",
    featured: false,
    size: "medium",
  },
  {
    title: "Centro de Sonografía PRE-VUE",
    slug: "centro-de-sonografia-pre-vue",
    description: "Official website for PRE-VUE Sonography Center in Puerto Rico. Features AI-powered 4D/HD Live imaging services, appointment scheduling, and a holistic wellness center integration.",
    image: "/projects/pre-vue.webp",
    tags: ["WordPress", "PHP", "CSS", "JavaScript"],
    category: "fullstack",
    github: "https://github.com/wolfslender",
    demo: "https://pre-vue.com/",
    featured: false,
    size: "medium",
  },
]

export const experience = [
  {
    company: "Co-Active Training Institute",
    position: "Frontend Web Developer (Part-time)",
    period: "2025 - Present",
    location: "Remote",
    description: "Collaborating on the maintenance and evolution of the main digital platform.",
    technologies: ["React", "JavaScript", "UI/UX", "Agile"],
    achievements: [
      "Contributing to the improvement of the user interface",
      "Participating in agile development cycles",
    ],
  },
  {
    company: "Dmed health care",
    position: "WordPress Specialist & Web Developer",
    period: "2018 - 2022",
    location: "Remote",
    description: "Led the development and maintenance of corporate websites using WordPress, focusing on custom themes and performance.",
    technologies: ["WordPress", "PHP", "MySQL", "JavaScript", "Custom Themes"],
    achievements: [
      "Developed and maintained custom WordPress themes and plugins",
      "Optimized site performance and security protocols",
      "Managed content updates and technical troubleshooting",
    ],
  },
  {
    company: "TRUENORTH Corp.",
    position: "Frontend Web Developer",
    period: "2022 - 2025",
    location: "Santo Domingo",
    description: "Specializing in web security, maintenance, SEO, and site management on Azure servers. Focused on performance optimization and usability.",
    technologies: ["WordPress", "WebFlow", "SEO", "Azure", "JavaScript", "CSS3"],
    achievements: [
      "Achieved a 25% increase in user retention",
      "Reduced loading times by 30% through optimization",
      "Implemented custom CMS solutions boosting efficiency by 40%",
      "Developed 15+ web projects with WebFlow",
    ],
  },
  {
    company: "CYBERNETIPS",
    position: "Fullstack Web Developer",
    period: "2017 - 2018",
    location: "Miami, FL (Remote)",
    description: "Specializing in backend development from scratch for high-traffic, large-scale projects and server administration.",
    technologies: ["HTML", "CSS", "JavaScript", "CPanel", "Cloud Architecture"],
    achievements: [
      "Managed and optimized servers in CPanel and Cloud environments",
      "Led optimization and maintenance of Cloud-based systems",
      "Ensured high availability and security of digital assets",
    ],
  },
]

export const education = [
  {
    school: "Liceo Minerva Mirabal",
    degree: "Computer Science, Bachelor's Degree",
    period: "Jun 2012 - Sep 2015",
    location: "Santo Domingo",
    description: "Graduated with a strong foundation in programming, algorithms, and information systems.",
  },
]

export const contact = {
  email: "contact@oliverodev.com",
  phone: "(829) 983-2502",
  location: "Santo Domingo, Dominican Republic",
  social: {
    github: "https://github.com/wolfslender",
    linkedin: "https://linkedin.com/in/alexis-olivero",
    instagram: "https://www.instagram.com/alexisfit97/",
  },
  calendly: "https://calendly.com/contact-oliverodev/30min",
}

export const plugins = {
  hero: {
    title: "WordPress Plugins",
    highlight: "Built to Scale",
    description: "Premium WordPress plugins designed to solve real problems. Clean code, regular updates, and dedicated support.",
  },
  plugins: [
    {
      title: "OliveroDev Media Audit",
      tagline: "Find unused media. Recover storage. Zero guesswork.",
      description: "The WordPress media library cleaner that actually works. Smart scanning detects unused files across posts, page builders, ACF fields, and WooCommerce — then lets you safely remove them with a risk-scoring system that prevents costly mistakes.",
      features: [
        "Smart scan: posts, pages, widgets, theme mods",
        "Used vs Unused dashboard with storage breakdown",
        "\"Where is it used?\" location finder per file",
        "Real-time scan progress counter",
        "Safe delete modal with thumbnail preview",
        "Export unused files as CSV",
        "Batch scanning & WP-Cron auto-scans",
      ] as string[],
      proFeatures: [
        "Deep Detection: Elementor, ACF, Divi, WooCommerce",
        "Risk Scoring (0–100) — know before you delete",
        "PRO Trash: restore files before permanent delete",
        "Bulk Cleanup by risk level (Low / Medium / All)",
        "Storage Analytics with visual charts",
        "Automated email reports (daily / weekly)",
        "Advanced exclusion rules (folder, size, author, MIME)",
        "3-day free trial — no credit card required",
      ] as string[],
      price: "From $29/year",
      plans: [
        { name: "1 Site", price: "$29", period: "/year", checkoutUrl: "https://checkout.freemius.com/plugin/23055/plan/47886/?trial=free" },
        { name: "Unlimited Sites", price: "$79", period: "/year", checkoutUrl: "https://checkout.freemius.com/plugin/23055/plan/49313/?trial=free" },
      ],
      url: "https://wordpress.org/plugins/oliverodev-media-audit/",
      freemiusUrl: "https://checkout.freemius.com/plugin/23055/plan/47886/?trial=free",
      icon: "🧹",
      color: "violet",
      bgColor: "bg-violet-500/5",
      stats: [
        { label: "Active Installs", value: "—", icon: "Users" },
        { label: "WordPress.org Rating", value: "—★", icon: "Star" },
        { label: "Last Updated", value: "May 2026", icon: "Clock" },
      ],
    },
  ],
}
